#!/usr/bin/env bash
set -euo pipefail

REPO="parabinda/moodleapp51"
WORKFLOW="build-android.yml"
BRANCH="main"
TO="parabinda@gmail.com"
SUBJECT="Android APK build"
WORKDIR="$HOME/github-artifacts"

mkdir -p "$WORKDIR"
cd "$WORKDIR"

echo "Starting workflow..."
gh workflow run "$WORKFLOW" --repo "$REPO" --ref "$BRANCH"

echo "Waiting for run to appear..."
sleep 10

RUN_ID="$(
    gh run list \
        --repo "$REPO" \
        --workflow "$WORKFLOW" \
        --limit 20 \
        --json databaseId,headBranch,createdAt,status \
        --jq "map(select(.headBranch == \"$BRANCH\")) | .[0].databaseId"
)"

if [ -z "$RUN_ID" ]; then
    echo "Could not find a workflow run for $WORKFLOW on branch $BRANCH."
    exit 1
fi

echo "Watching run: $RUN_ID"
gh run watch "$RUN_ID" --repo "$REPO" --exit-status

rm -rf "$WORKDIR/download" "$WORKDIR/unzipped"
mkdir -p "$WORKDIR/download" "$WORKDIR/unzipped"

echo "Downloading artifacts..."
gh run download "$RUN_ID" --repo "$REPO" --dir "$WORKDIR/download"

APK="$(find "$WORKDIR/download" -type f -name '*.apk' | head -n 1 || true)"

if [ -z "$APK" ]; then
    ZIP="$(find "$WORKDIR/download" -type f -name '*.zip' | head -n 1 || true)"

    if [ -z "$ZIP" ]; then
        echo "No APK or zip artifact found."
        echo "Downloaded files:"
        find "$WORKDIR/download" -type f -print
        exit 1
    fi

    echo "Unzipping artifact: $ZIP"
    unzip -o "$ZIP" -d "$WORKDIR/unzipped" >/dev/null
    APK="$(find "$WORKDIR/unzipped" -type f -name '*.apk' | head -n 1 || true)"
fi

if [ -z "$APK" ]; then
    echo "No APK found after downloading/unzipping artifacts."
    echo "Downloaded files:"
    find "$WORKDIR/download" -type f -print
    echo "Unzipped files:"
    find "$WORKDIR/unzipped" -type f -print
    exit 1
fi

echo "Found APK: $APK"

BOUNDARY="====apk-boundary-$(date +%s)==="
FILENAME="$(basename "$APK")"

{
    echo "To: $TO"
    echo "Subject: $SUBJECT"
    echo "MIME-Version: 1.0"
    echo "Content-Type: multipart/mixed; boundary=\"$BOUNDARY\""
    echo
    echo "--$BOUNDARY"
    echo "Content-Type: text/plain; charset=UTF-8"
    echo
    echo "Attached is the APK generated by GitHub Actions."
    echo
    echo "Repository: $REPO"
    echo "Workflow: $WORKFLOW"
    echo "Branch: $BRANCH"
    echo "Run ID: $RUN_ID"
    echo
    echo "--$BOUNDARY"
    echo "Content-Type: application/vnd.android.package-archive; name=\"$FILENAME\""
    echo "Content-Transfer-Encoding: base64"
    echo "Content-Disposition: attachment; filename=\"$FILENAME\""
    echo
    base64 "$APK"
    echo
    echo "--$BOUNDARY--"
} | msmtp "$TO"

echo "Mail sent to $TO with APK attachment: $FILENAME"
